baseurl = "https://elcineksi.com/"
title = "Elçin Ekşi"
theme = "hugo-theme-novela"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

  [[params.navlinks]]
  name = "photos/"
  url = "photos/"
[social]
 twitter = "https://twitter.com/AmaEksi"
 instagram = "https://www.instagram.com/eksielcin/"
 researchgate = "asdasd"
